# Jekyll
permalink: /:year/:title/
paginate: 10
exclude: []
name: Useful Blog
baseurl: 
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
defaults:
    -
        scope:
              type: "posts"
        values:
              author: "Anonymous"
    -
        scope:
              path: ""
        values:
              parent: "http://useful.io/"
              disqus: "disqus_VLf7F1EkG7"